### PR TITLE
Feature/api v3

### PR DESCRIPTION
**Pull request by kamilbednarz**
Hey @relrod,

here is a draft of a pull request that covers the migration to API v3.

I also refactored the code (separated the logic responsible for HTTP requests/responses) and the organized specs (mostly just wrapped them in `describe` blocks by method).

### CODE REVIEW

**Comment by relrod** [comment]
@kamilbednarz At a quick glance this looks fine to me. I'm a bit out of touch with Ruby practices - is there a way to release a beta version of this and let people test it?

**Comment by kamilbednarz** [comment]
Sure, I'll release a beta version and test it with a project for my client.

**Comment by kamilbednarz** [comment]
Hey @relrod, I created a new gem version, can you either push it to rubygems, or allow me to push new versions (My email is in my github profile)? 

The tag is: `6.0.0.beta.1`

**Comment by relrod** [comment]
@kamilbednarz Added you on rubygems. Thanks so much for your work on this!

**Pull request merged**
